### ISSUE TITLE
Provide documentation for the VMWare controller

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/documentation#1]
Based on  [VMWare controller contribution issue #3](https://github.com/servicecatalog/development/issues/3), @mdehn raised a [VMWare controller feature issue #23](https://github.com/servicecatalog/development/issues/23). 

It is about ensuring enterprise-ready quality for the contributed VMWare controller. Among other issues like internationalization, integration tests, installation scripts is also a good documentation. 

From the provided information of contributors in issue  [#3](https://github.com/servicecatalog/development/issues/3), the VMWare controller should support similar operations as existing controllers. The specific issues will be known after the reviewing the commits and testing.

**Comment by SuessI** [comment]
A new manual, VMware vSphere Integration, is available. It describes how to
offer and use virtual machines provisioned on a VMware vSphere server through services in
OSCM. Its structure and contents is analogous to the previous integration manuals. It has been written and reviewed according to the standard processes.
