### ISSUE TITLE
Description for TKey in vCenter.csv is difficult to understand

### ISSUE THREAD

**Issue by misako0927** [servicecatalog/documentation#2]
[Version]
v16.1 GA1
BES_MASTER_DELIVERY-744-20160722124302

[detail of issue]
Description for TKey of vCenter.csv in VMware Integration Guide A.5 vSphere Configuration is difficult to understand. Please update to these description which I got information from dev side (See https://github.com/servicecatalog/development/issues/161):

  The TKey parameter is a unique identifier of the vcenter in the controller database. It has nothing to do with the target vSphere system.

And also this TKey only use integer. This information is also needed for this description.

**Comment by gertipoppel** [comment]
Updated the description in file DocSources12/en/VMWareIntegrationGuide/Appendix/r_CSVFormat.xml

**Comment by ghost** [comment]
[Build] 2016/08/18 verified TKey description
