### ISSUE TITLE
Wrong link to oscm-app/controller

### ISSUE THREAD

**Issue by kolodziejczykm** [servicecatalog/documentation#5]
[Version]
Open Service Catalog Manager - Amazon Web Services Integration V17.6.0

[Issue]

In the PDF mentioned above the link that should give access to see all the subscriptions and the detailed information is wrong and dosen't work: (Chapter 4.2)

![image](https://user-images.githubusercontent.com/34572039/35507777-3011d0c0-04ee-11e8-8f15-ce6c5c07d5e8.png)

The correct format should be: 
![correctlink](https://user-images.githubusercontent.com/34572039/35507945-c8ce2eee-04ee-11e8-97cf-6c5cf6cc4964.JPG)

**Comment by gertipoppel** [comment]
Fixed PDFs are available on 
https://github.com/servicecatalog/documentation/blob/ESCM/README.md
