### ISSUE TITLE
document proxy settings in var.env

### ISSUE THREAD

**Issue by ghost** [servicecatalog/documentation#6]
[Build] 17.6 2018/02/13

[Details]
https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-deployer/templates/var.env.template
has new proxy settings. Please document these.

**Comment by gertipoppel** [comment]
Added the description together with two other new settings according to 
https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-deployer/templates/var.env.template
to the Operator's Guide 2018-22-02
